meta:
  title: Garlic butter
ingredients:
  - Butter (slightly salted)
  - 1 block
  - Parsley
  -
  - Garlic
  - 10/12 cloves
  - Black pepper
  -
method:
  - Sit butter at room temperature
  - Mince garlic. Add to butter
  - Chop parsley. Add to butter
  - Mix
  - Wrap as sausage in parchment paper and set in fridge
